Addpage
thampaponn/GoodPort pull request #17
Opened 2023-10-08 18:51 UTC by thampaponn

input type file เอาไงดี

2023-10-09 03:09 UTC, madara1150 requested changes

2023-10-09 03:09 UTC, madara1150 commented on screens/AddPortScreen.tsx
> +      <InputForm title='ชื่อโครงงานภาษาไทย' />
อย่าใช้ inputForm ให้เรียกใช้ Input ตรงๆเลย เพราะจะทำ backend ยาก
```suggestion
      <Text style={styles.formText}>{'ชื่อโครงงานภาษาไทย'}</Text>
      <Input  style={styles.textInput}  inputContainerStyle={{ borderBottomWidth: 0 }}/>
```

2023-10-09 03:09 UTC, madara1150 commented on components/ui/InputForm.tsx
ลบไฟล์นี้ออกเลยก็ได้ห้ามใช้

2023-10-09 03:09 UTC, madara1150 commented on screens/AddPortScreen.tsx
> +import { Button, Card, Chip, Input } from "@rneui/themed";
อันไหนไม่ใช้ลบออก

2023-10-09 03:09 UTC, madara1150 commented on screens/AddPortScreen.tsx
> +import { View, Text, SafeAreaView } from 'react-native'
อันไหนไม่ใช้ลบออก

2023-10-09 03:09 UTC, madara1150 commented on screens/AddPortScreen.tsx
> +import { InputForm } from '../components/ui/InputForm';
ลบออก

2023-10-09 03:09 UTC, madara1150 commented on screens/MainPageScreen.tsx
> +            key={key}
ควรเป็น index
```suggestion
        {PostMockup.map((post, index) => (
          <ProductCard
            key={index}
```

2023-10-09 03:09 UTC, madara1150 commented on screens/NotificationScreen.tsx
> +              <View key={key} style={{ marginTop: 10 }}>
```suggestion
            mockupData.map((data, index) => (
              <View key={index} style={{ marginTop: 10 }}>
```

2023-10-09 03:09 UTC, madara1150 commented on screens/ProductDetail.tsx
> +              key={key}
```suggestion
          {ImageMockup.map((image, index) => (
            <Card.Image
              key={index}
```

2023-10-09 03:09 UTC, madara1150 commented on screens/ProductDetail.tsx
> +            <Card key={key} containerStyle={{ borderRadius: 12 }}>
```suggestion
          {fileMockup.map((file, index) => (
            <Card key={index} containerStyle={{ borderRadius: 12 }}>
```

2023-10-09 03:11 UTC, madara1150 commented
@thampaponn  แก้เสดแล้ว แคปรูปลงไว้ด้วย

2023-10-09 04:36 UTC, thampaponn commented
AddPortScreen
<img width="1265" alt="image" src="https://github.com/thampaponn/GoodPort/assets/88426179/075f2483-71d8-492d-8fd3-d5235dc595dc">

2023-10-09 04:38 UTC, thampaponn commented
MainPageScreen
<img width="584" alt="image" src="https://github.com/thampaponn/GoodPort/assets/88426179/d2d07d76-3a5c-4afd-b4f1-0057c9e7c434">

2023-10-09 04:39 UTC, thampaponn commented
NotificationScreen
<img width="739" alt="image" src="https://github.com/thampaponn/GoodPort/assets/88426179/2b6eae58-7ee4-489b-9f44-201c9c966c5f">
<img width="739" alt="image" src="https://github.com/thampaponn/GoodPort/assets/88426179/82e8e5cb-c520-4dab-9c14-59924e4dbfba">

2023-10-09 04:40 UTC, thampaponn commented
ProductDetail
<img width="739" alt="image" src="https://github.com/thampaponn/GoodPort/assets/88426179/5cf34cd0-7794-4521-a70d-4a5cdba6d6c5">

2023-10-12 10:51 UTC, madara1150 commented
@thampaponn merge ได้

2023-10-14 04:44 UTC, merged